livebook live video input
membraneframework-labs/membrane_kino_plugin pull request #15
Opened 2024-05-21 17:22 UTC by bartkrak

solves: https://github.com/membraneframework-labs/livebook_to_model/issues/1

2024-05-22 17:01 UTC, bartkrak commented
I've split audio and video input into separate bins.
Also updated all demos to work after my changes.

2024-06-03 10:12 UTC, FelonEkonom requested changes

2024-06-03 10:12 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source_remote_stream_video.ex
> +end
I guess that `Membrane.Kino.Input` can handle both audio and video at the same time, so having two separate elements that both can handle only one type of media seems to not be good solution.

Write one element that:
1. Receives `Kino.Input` in opts and registers it
2. Has 2 types of dynamic pads, `:audio` and `:video`
3. In `handle_pad_added` asserts that there is up to one `:audio` and up to one `:video` pad.
4. In `handle_info({:video_frame, ...` sends video frame on the only one `:video` pad (and similarly on `:audio_frame`)
5. Sends proper stream format on the proper pad

Similarly, write only one `SourceBin`, that has analogical pads and sets up `:demuxer` in `handle_pad_added(Pad.ref(:audio, ...` and sets up `:parser` in `handle_pad_added(Pad.ref(:video, ...`

2024-06-03 10:12 UTC, FelonEkonom commented on lib/membrane/kino/player/player_bin_sink.ex
>    """
Why have you deleted this?

2024-06-03 10:12 UTC, FelonEkonom commented on lib/assets/input/main.css
>  }
Please add mirror reflection to the played video. It would look more natural. I know that it is a matter of adding one parameter to the `<video` html tag

2024-06-17 12:53 UTC, FelonEkonom requested changes
Reply or solve old comments from my previous review

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    {[], %{state | tracks: Map.put(state.tracks, pad, Track)}}
You use `state.tracks` only to have a set of all pads. Use `ctx.pads` instead of it

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    |> Enum.filter(fn {_membrane_pad, pad_name, _ref} -> pad_name == target end)
Match on `Pad.ref(...)`, don't rely on `membrane_core` internal implementation of pad. The way how it is implemented is a part of private API and it can change without marking it as a breaking change

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    {[notify_parent: %{framerate: framerate}], state}
Let the parent notification be a tuple `{:framerate, value}` instead of map

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +        %{stream_format: stream_format, end_of_stream?: end_of_stream} =
```suggestion
        %{stream_format: stream_format, end_of_stream?: end_of_stream?} =
```

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +      if video_pad != nil do
if `video_pad == nil`, `actions` will be `nil` too, while it should be `[]` (I guess so)

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +      if video_pad != nil do
And it means that this case is not covered by tests

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    }
Can we set some timestamp fields here?

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +      end
You can write `[end_of_stream: ...]` instead of `[{:end_of_stream, ...`

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    end
Similar raise would be appreciated in the bin too. BTW wherever it is possible, use `__MODULE__` macro instead of writing `Kino.Input.Source` explicitly

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_bin_source.ex
> +      child(:remote_stream, %Kino.Input.Source{kino: options.kino})
Rename this child to sth like `:kino_input_source` or `:kino_input`

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +        raise KinoSourceAlreadyOccupiedError, message: "Kino source already occupied"
Remove definition of this exception and raise normal `RuntimeError` with message like `"Cannot register to KinoInput because it is already occupied"`

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/player/player_sink.ex
> -  ```
Why have you removed this example?

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/player/player_bin_sink.ex
>    """
Unanswered

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input.ex
> +  #
leftover

2024-06-17 12:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    kino_mode = Kino.JS.Live.call(options.kino, {:get_type})
1. Don't wrap `:get_type` into a tuple, there is no reason to do it
2. I would move this `call` to `handle_setup`

2024-06-17 12:53 UTC, FelonEkonom commented on examples/video_and_audio.livemd
>  Logger.configure(level: :error)
Please set it to `:warning` instead of `:error`

2024-06-17 12:53 UTC, FelonEkonom commented on README.md
> +Supports playing and recording audio and video streams.
`recording` -> `accessing`
For me, the first association with `recording` audio and video is to save it, not to get it

2024-06-17 14:03 UTC, FelonEkonom commented on lib/assets/input/main.css
>  }
I thought about output, mea culpa

2024-06-24 09:53 UTC, FelonEkonom requested changes

2024-06-24 09:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +
You duplicate the logic in these two callbacks. Create private function `handle_frame(pad, info, binary, state)` and put this logic there.

2024-06-24 09:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +      end
```suggestion
[end_of_stream: audio_pad, end_of_stream: video_pad]
|> Enum.reject(fn {:end_of_stream, pad} -> pad == nil end)
```

2024-06-24 09:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    # end
leftover

2024-06-24 09:53 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    |> List.first()
Use `Enum.find`

2024-06-24 09:53 UTC, FelonEkonom commented on lib/membrane/kino/player/player_bin_sink.ex
> +
What is the benefit of having this bin? IMO it can be deleted

2024-06-24 09:53 UTC, FelonEkonom commented on examples/video_capture.livemd
> +```
On Firefox I get an error: 
```11:37:39.588 [error] <0.4859.0>/:source/ Terminating with reason: {:membrane_child_crash, :kino_input, {%RuntimeError{message: "Cannot register KinoInput because it is already occupied"}, [{Membrane.Kino.Input.Source, :handle_setup, 2, [file: ~c"lib/membrane/kino/input/input_source.ex", line: 47]}, {Membrane.Core.CallbackHandler, :exec_callback, 4, [file: ~c"lib/membrane/core/callback_handler.ex", line: 139]}, {Membrane.Core.CallbackHandler, :exec_and_handle_callback, 5, [file: ~c"lib/membrane/core/callback_handler.ex", line: 69]}, {Membrane.Core.Element.LifecycleController, :handle_setup, 1, [file: ~c"lib/membrane/core/element/lifecycle_controller.ex", line: 62]}, {Membrane.Core.Element, :handle_continue, 2, [file: ~c"lib/membrane/core/element.ex", line: 166]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1067]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 977]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}

11:37:39.588 [error] <0.4859.0>/ Terminating with reason: {:membrane_child_crash, :source, {:membrane_child_crash, :kino_input, {%RuntimeError{message: "Cannot register KinoInput because it is already occupied"}, [{Membrane.Kino.Input.Source, :handle_setup, 2, [file: ~c"lib/membrane/kino/input/input_source.ex", line: 47]}, {Membrane.Core.CallbackHandler, :exec_callback, 4, [file: ~c"lib/membrane/core/callback_handler.ex", line: 139]}, {Membrane.Core.CallbackHandler, :exec_and_handle_callback, 5, [file: ~c"lib/membrane/core/callback_handler.ex", line: 69]}, {Membrane.Core.Element.LifecycleController, :handle_setup, 1, [file: ~c"lib/membrane/core/element/lifecycle_controller.ex", line: 62]}, {Membrane.Core.Element, :handle_continue, 2, [file: ~c"lib/membrane/core/element.ex", line: 166]}, {:gen_server, :try_handle_continue, 3, [file: ~c"gen_server.erl", line: 1067]}, {:gen_server, :loop, 7, [file: ~c"gen_server.erl", line: 977]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}}

11:37:39.758 [error] GenServer #PID<0.4797.0> terminating
** (Membrane.Kino.Player.PlayerError) Kino Player doesn't support multiple clients
    (membrane_kino_plugin 0.4.0) lib/membrane/kino/player.ex:179: Membrane.Kino.Player.handle_event/3
    (kino 0.9.4) lib/kino/js/live/server.ex:105: Kino.JS.Live.Server.call_handle_info/3
    (kino 0.9.4) lib/kino/js/live/server.ex:60: Kino.JS.Live.Server.handle_info/2
    (stdlib 5.1.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:event, "error", "Kino Player doesn't support multiple clients", %{origin: "axggm3i4d665be2g", ref: "hhnraivc4iomgswzloou4grbsdprpplk"}}
```

On Safari I get an error:
```
11:42:26.479 [error] GenServer #PID<0.4945.0> terminating
** (Membrane.Kino.Input.InputError) Error while opening audio stream: mimeType is not supported
    (membrane_kino_plugin 0.4.0) lib/membrane/kino/input.ex:153: Membrane.Kino.Input.handle_event/3
    (kino 0.9.4) lib/kino/js/live/server.ex:105: Kino.JS.Live.Server.call_handle_info/3
    (kino 0.9.4) lib/kino/js/live/server.ex:60: Kino.JS.Live.Server.handle_info/2
    (stdlib 5.1.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:event, "error", "Error while opening audio stream: mimeType is not supported", %{origin: "nbyzkduddgkzimex", ref: "qp4nzpaeqxlfxbupjbt23653pqjgf5vm"}}
```
Let's fix it, if it is not very hard to do it. Otherwise, add a comment about supported browsers.

2024-06-24 09:53 UTC, FelonEkonom commented on examples/video_capture.livemd
> +```
Merge these two sections, because I cannot reevaluate only the second one without getting an error

2024-06-24 09:53 UTC, FelonEkonom commented on examples/video_capture.livemd
> +RCPipeline.exec_actions(pipeline, spec: loopback)
Start player, input and pipeline under `Kino` supervisor, so the processes will be killed after reevaluating the livebook cell. You can use this function: https://hexdocs.pm/kino/Kino.html#start_child!/1

2024-06-24 11:16 UTC, FelonEkonom commented
I get these logs, when I run `video_capture.livemd`:
```
13:11:30.142 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.254 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.254 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.254 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.523 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.523 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping

13:11:30.524 [warning] <0.5233.0>/:aac_encoder PTS values are overlapping
```
Relax the constraint in AAC plugin, so the person running the demo doesn't receive these unnecessary logs.

2024-06-26 08:22 UTC, mat-hek commented on examples/video_capture.livemd
> +```
Yup, we target only Chrome for now. Supporting other browsers is tricky as they output weird media formats AFAIK. We could improve this error message though, so it also says 'Note that Membrane Kino plugin may not work in browsers other than Google Chrome'

2024-06-26 12:56 UTC, mkopcins requested changes

2024-07-04 09:57 UTC, mkopcins commented on lib/assets/input/main.js
> +  const streamAudioTracks = sending_error(async () => {
Not really something we need to be concerned about but  `sending_error` here would never work because of the `try catch` block inside

2024-07-04 09:57 UTC, mkopcins commented on lib/assets/input/main.js
> +  const streamVideoTracks = sending_error(async () => {
Like above

2024-07-25 07:39 UTC, mkopcins approved these changes

2024-07-25 12:23 UTC, FelonEkonom commented on lib/membrane/kino/input/input_bin_source.ex
> +      |> length()
Use https://hexdocs.pm/elixir/1.17.2/Enum.html#count/2 instead

2024-07-25 12:23 UTC, FelonEkonom commented on lib/membrane/kino/input/input_bin_source.ex
> +  defp assert_pad_count(name, ctx) do
```suggestion
  defp assert_pad_number!(name, ctx) do
```
Functions that check the assertion and raise if the condition in it isn't met should end with `!`

2024-07-25 12:23 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +    accepted_format: @audio_stream_format,
Revert changes in these lines, because otherwise we will have `accepted_format: @audio_stream_format` in the module docs

2024-07-25 12:23 UTC, FelonEkonom commented on lib/membrane/kino/input/input_source.ex
> +      |> length()
as in `input_bin_source.ex`

2024-07-25 12:23 UTC, FelonEkonom commented on lib/membrane/kino/player/player_bin_sink.ex
>    """
I see that this file is deleted now

2024-07-25 12:27 UTC, FelonEkonom requested changes
Merge linked PR, release the aac fdk plugin and bump the dependency before merging PR here, in kino plugin

https://github.com/membraneframework/membrane_aac_fdk_plugin/pull/60

2024-07-26 13:56 UTC, FelonEkonom approved these changes
I recommend using app.grammarly.com when you write or change documentation. It finds for example places where you missed `the` or other typos

2024-08-06 14:08 UTC, merged