MS-440 Create kino microphone input
membraneframework-labs/membrane_kino_plugin pull request #8
Opened 2023-03-28 11:37 UTC by Janix4000

2023-04-27 09:11 UTC, mat-hek commented
@Janix4000 I get the following error when I try to run the audio and video example:
```

11:09:57.776 [error] GenServer #PID<0.4385.0> terminating
** (Membrane.StreamFormatError) Stream format: %Membrane.H264{width: 1920, height: 1080, profile: :high, alignment: :au, nalu_in_metadata?: false, framerate: {60, 1}} is not matching accepted format pattern in def_input_pad
for pad :video in Membrane.Kino.Player.Sink

    (membrane_core 0.11.3) lib/membrane/core/element/stream_format_controller.ex:96: anonymous fn/4 in Membrane.Core.Element.StreamFormatController.validate_stream_format!/3
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (membrane_core 0.11.3) lib/membrane/core/element/stream_format_controller.ex:94: Membrane.Core.Element.StreamFormatController.validate_stream_format!/3
    (membrane_core 0.11.3) lib/membrane/core/element/stream_format_controller.ex:64: Membrane.Core.Element.StreamFormatController.exec_handle_stream_format/4
    (membrane_core 0.11.3) lib/membrane/core/element.ex:183: Membrane.Core.Element.handle_info/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {Membrane.Core.Message, :stream_format, %Membrane.H264{width: 1920, height: 1080, profile: :high, alignment: :au, nalu_in_metadata?: false, framerate: {60, 1}}, [for_pad: {Membrane.Pad, :video, #Reference<0.1596432836.420478978.18292>}]}
```

2023-04-27 09:16 UTC, mat-hek commented
The audio demo says it uses a video player 🤔 and it sometimes crashes with:
```
11:15:06.252 [error] GenServer #PID<0.460.0> terminating
** (stop) exited in: GenServer.call(#PID<0.339.0>, {:create, 43.06640625}, 5000)
    ** (EXIT) time out
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (membrane_kino_plugin 0.1.0) lib/membrane/kino/player_sink.ex:183: Membrane.Kino.Player.Sink.create_player/2
    (membrane_kino_plugin 0.1.0) lib/membrane/kino/player_sink.ex:165: Membrane.Kino.Player.Sink.handle_start_of_stream/3
    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:138: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:62: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 0.11.3) lib/membrane/core/element/event_controller.ex:79: Membrane.Core.Element.EventController.do_exec_handle_event/4
    (membrane_core 0.11.3) lib/membrane/core/element/buffer_controller.ex:43: Membrane.Core.Element.BufferController.handle_buffer/3
    (membrane_core 0.11.3) lib/membrane/core/element.ex:177: Membrane.Core.Element.handle_info/2
Last message: {Membrane.Core.Message, :buffer, [%Membrane.Buffer{payload: <<255, 241, 80, 64, 22, 127, 252, 222, 2, 0, 76, 97, 118, 99, 53, 56, 46, 53, 52, 46, 49, 48, 48, 0, 2, 116, 171, 84, 216, 228, 109, 89, 85, 223, 63, 90, 185, 89, 89, 239, 223, 227, 87, 34, 32, ...>>, pts: 0, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 32, 159, 252, 1, 40, 152, 218, 224, 173, 215, 9, 140, 3, 110, 146, 97, 55, 35, 34, 1, 221, 196, 226, 236, 28, 121, 154, 212, 254, 253, 119, 215, 71, 183, 28, 76, 255, 226, 87, 158, ...>>, pts: 10240000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 26, 159, 252, 1, 18, 245, 172, 208, 139, 27, 16, 172, 255, 176, 22, 192, 1, 17, 4, 16, 0, 93, 68, 160, 136, 133, 42, 84, 46, 218, 119, 72, 212, 44, 32, 53, 216, 88, 213, ...>>, pts: 20480000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 23, 191, 252, 0, 230, 53, 172, 236, 244, 26, 152, 88, 241, 159, 145, 237, 174, 26, 33, 42, 42, 12, 82, 148, 20, 170, 80, 166, 170, 149, 103, 10, 178, 168, 60, 144, 146, 114, ...>>, pts: 10240000000 <|> 147, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 27, 127, 252, 0, 228, 53, 172, 209, 6, 34, 12, 138, 130, 19, 189, 63, 52, 124, 107, 83, 66, 0, 21, 74, 80, 82, 148, 161, 136, 229, 39, 43, 153, 202, 164, 98, 149, ...>>, pts: 40960000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 24, 95, 252, 0, 234, 53, 172, 236, 231, 10, 13, 78, 43, 120, 207, 145, 237, 122, 156, 9, 25, 106, 133, 82, 148, 160, 165, 82, 132, 243, 77, 44, 173, 44, 171, 2, ...>>, pts: 51200000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 28, 31, 252, 0, 228, 53, 172, 244, 70, 60, 17, 136, 137, 34, 9, 28, 191, 129, 241, 174, 36, 64, 0, 82, 148, 81, 74, 80, 59, 164, 86, 228, 46, 0, 231, ...>>, pts: 20480000000 <|> 147, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 23, 31, 252, 0, 238, 53, 172, 236, 244, 56, 185, 203, 244, 31, 23, 195, 80, 68, 50, 202, 170, 82, 130, 148, 165, 9, 234, 121, 106, 105, 106, 89, 4, 228, ...>>, pts: 10240000000 <|> 63, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 28, 127, 252, 0, 228, 53, 172, 240, 116, 35, 133, 146, 135, 34, 9, 28, 191, 129, 241, 174, 46, 0, 0, 82, 148, 41, 74, 80, 62, 224, 91, 104, 135, ...>>, pts: 81920000000 <|> 441, dts: nil, metadata: %{}}], [for_pad: {Membrane.Pad, :audio, #Reference<0.3252172004.3910402053.66272>}]}
```

2023-04-27 09:19 UTC, mat-hek commented
And I don't see examples for the sources

2023-05-08 09:06 UTC, mat-hek reviewed
see the comments above

2023-05-19 12:53 UTC, mat-hek commented
There's a race condition triggered by evaluating the last cell without running the previous ones (they're triggered automatically) causing the following error:

```
14:50:49.110 [error] GenServer #PID<0.3213.0> terminating
** (stop) exited in: GenServer.call(#PID<0.3199.0>, {:create, 43.06640625}, 5000)
    ** (EXIT) time out
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (membrane_kino_plugin 0.1.0) lib/membrane/kino/player_sink.ex:188: Membrane.Kino.Player.Sink.create_player/2
    (membrane_kino_plugin 0.1.0) lib/membrane/kino/player_sink.ex:169: Membrane.Kino.Player.Sink.handle_start_of_stream/3
    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:138: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.11.3) lib/membrane/core/callback_handler.ex:62: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 0.11.3) lib/membrane/core/element/event_controller.ex:79: Membrane.Core.Element.EventController.do_exec_handle_event/4
    (membrane_core 0.11.3) lib/membrane/core/element/buffer_controller.ex:43: Membrane.Core.Element.BufferController.handle_buffer/3
    (membrane_core 0.11.3) lib/membrane/core/element.ex:177: Membrane.Core.Element.handle_info/2
Last message: {Membrane.Core.Message, :buffer, [%Membrane.Buffer{payload: <<255, 241, 80, 64, 22, 127, 252, 222, 2, 0, 76, 97, 118, 99, 53, 56, 46, 53, 52, 46, 49, 48, 48, 0, 2, 116, 171, 84, 216, 228, 109, 89, 85, 223, 63, 90, 185, 89, 89, 239, 223, 227, 87, 34, 32, ...>>, pts: 0, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 32, 159, 252, 1, 40, 152, 218, 224, 173, 215, 9, 140, 3, 110, 146, 97, 55, 35, 34, 1, 221, 196, 226, 236, 28, 121, 154, 212, 254, 253, 119, 215, 71, 183, 28, 76, 255, 226, 87, 158, ...>>, pts: 10240000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 26, 159, 252, 1, 18, 245, 172, 208, 139, 27, 16, 172, 255, 176, 22, 192, 1, 17, 4, 16, 0, 93, 68, 160, 136, 133, 42, 84, 46, 218, 119, 72, 212, 44, 32, 53, 216, 88, 213, ...>>, pts: 20480000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 23, 191, 252, 0, 230, 53, 172, 236, 244, 26, 152, 88, 241, 159, 145, 237, 174, 26, 33, 42, 42, 12, 82, 148, 20, 170, 80, 166, 170, 149, 103, 10, 178, 168, 60, 144, 146, 114, ...>>, pts: 10240000000 <|> 147, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 27, 127, 252, 0, 228, 53, 172, 209, 6, 34, 12, 138, 130, 19, 189, 63, 52, 124, 107, 83, 66, 0, 21, 74, 80, 82, 148, 161, 136, 229, 39, 43, 153, 202, 164, 98, 149, ...>>, pts: 40960000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 24, 95, 252, 0, 234, 53, 172, 236, 231, 10, 13, 78, 43, 120, 207, 145, 237, 122, 156, 9, 25, 106, 133, 82, 148, 160, 165, 82, 132, 243, 77, 44, 173, 44, 171, 2, ...>>, pts: 51200000000 <|> 441, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 28, 31, 252, 0, 228, 53, 172, 244, 70, 60, 17, 136, 137, 34, 9, 28, 191, 129, 241, 174, 36, 64, 0, 82, 148, 81, 74, 80, 59, 164, 86, 228, 46, 0, 231, ...>>, pts: 20480000000 <|> 147, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 23, 31, 252, 0, 238, 53, 172, 236, 244, 56, 185, 203, 244, 31, 23, 195, 80, 68, 50, 202, 170, 82, 130, 148, 165, 9, 234, 121, 106, 105, 106, 89, 4, 228, ...>>, pts: 10240000000 <|> 63, dts: nil, metadata: %{}}, %Membrane.Buffer{payload: <<255, 241, 80, 64, 28, 127, 252, 0, 228, 53, 172, 240, 116, 35, 133, 146, 135, 34, 9, 28, 191, 129, 241, 174, 46, 0, 0, 82, 148, 41, 74, 80, 62, 224, 91, 104, 135, ...>>, pts: 81920000000 <|> 441, dts: nil, metadata: %{}}], [for_pad: {Membrane.Pad, :audio, #Reference<0.2141576257.800325637.66363>}]}
```

This error seems to happen when kino is occupied, a moment after `Kino source already occupied` error.

2023-05-19 13:41 UTC, mat-hek requested changes

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input.ex
> +  use Kino.JS, assets_path: "lib/assets/audio_input"
I think that assets should live in `priv`

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input.ex
> +defmodule Membrane.Kino.Input do
no moduledoc

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input.ex
> +  def new(_type \\ :audio, opts \\ []) do
- no docs or specs, do you have credo enabled?
- why is audio the default?

2023-05-19 13:41 UTC, mat-hek commented on examples/video_and_audio.livemd
>  kino = Membrane.Kino.Player.new(:both)
both is quite ambiguous, maybe `[:audio, :video]`?

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input.ex
> +      if ctx.assign.client == nil do
what's `ctx.assign`?

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input_source.ex
> +defmodule Membrane.Kino.InputSource do
maybe just `Kino.Source`?

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input_source.ex
> +              ]
- doesn't it support only `Membrane.Kino.Input`?
- it should create and render an instance of `Membrane.Kino.Input` when it's not provided

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/input_source.ex
> +        duration: Time.milliseconds(duration)
do we need that?

2023-05-19 13:41 UTC, mat-hek commented on lib/membrane/kino/player.ex
> +  def new(type \\ :video, opts \\ []) do
again, why is video the default?

2023-05-19 13:41 UTC, mat-hek commented on test/decode_microphone_test.exs
> +    # Logger.configure(level: :error)
```suggestion
```

2023-05-19 13:49 UTC, Janix4000 commented on lib/membrane/kino/input.ex
> +      if ctx.assign.client == nil do
Typo

2023-05-19 13:51 UTC, Janix4000 commented on lib/membrane/kino/input.ex
> +  use Kino.JS, assets_path: "lib/assets/audio_input"
Official Kino moudules follow this convention, see https://github.com/livebook-dev/kino/tree/main/lib/assets

2023-05-19 14:35 UTC, Janix4000 commented on lib/membrane/kino/input_source.ex
> +        duration: Time.milliseconds(duration)
Not sure, but we can keep it for a potential future compatibility

2023-05-19 14:36 UTC, Janix4000 commented on lib/membrane/kino/input_source.ex
> +defmodule Membrane.Kino.InputSource do
`Kino.Input.Source`? It follows convention `Kino.Player.Sink`

2023-05-22 09:03 UTC, mat-hek commented on lib/membrane/kino/input_source.ex
> +        duration: Time.milliseconds(duration)
what is future compatibility? 🤔

2023-05-22 10:10 UTC, mat-hek requested changes

2023-05-24 11:33 UTC, mat-hek commented on lib/membrane/kino/player.ex
> +    audio = Map.get(buffers, :audio) || <<>>
```suggestion
    video = Map.get(buffers, :video, <<>>)
    audio = Map.get(buffers, :audio, <<>>)
```

2023-05-24 11:33 UTC, mat-hek commented on lib/membrane/kino/player.ex
> +    info = info |> Map.put(:video_size, byte_size(video)) |> Map.put_new(:type, :both)
why is the `type` always `:both`?

2023-05-24 11:33 UTC, mat-hek commented on lib/membrane/kino/player/player_sink.ex
>    def handle_write({_mod, pad, _ref}, %Buffer{payload: payload}, _ctx, state) do
```suggestion
  def handle_write(Pad.ref(pad, _id), %Buffer{payload: payload}, _ctx, state) do
```

2023-05-24 11:33 UTC, mat-hek commented on lib/membrane/kino/player/player_sink.ex
> +        if exist do
```suggestion
      Enum.reduce(type, %{}, fn {type, exists?}, acc ->
        if exists? do
```

2023-05-24 11:33 UTC, mat-hek commented on lib/membrane/kino/input.ex
> +      ref = Process.monitor(from)
cool, do that in the player too

2023-05-30 10:07 UTC, Janix4000 commented on lib/membrane/kino/player.ex
> +    info = info |> Map.put(:video_size, byte_size(video)) |> Map.put_new(:type, :both)
It should be removed

2023-05-30 10:11 UTC, Janix4000 commented on lib/membrane/kino/input.ex
> +      ref = Process.monitor(from)
We decided to not do it right now

2023-05-30 10:13 UTC, mat-hek approved these changes

2023-05-30 11:28 UTC, merged